name: Golang (test)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic $(find . -name go.mod | sed "s/go.mod/.../g")
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token:
          files: coverage.out
          fail_ci_if_error: true
